### ISSUE TITLE
EDA - 3 - Raw Feature importance and selection Pipeline

### ISSUE THREAD

**Issue by swainshashwat** [sandipbhuyan/trAIn#14]
- [ ] Display basic feature importance using Random Forests
- [ ] Add auto-feature selection: percentile-based
- [ ] Add auto-feature selection: linear-model-based
