### ISSUE TITLE
EDA - 1 - Auto-Graph Graph generation module

### ISSUE THREAD

**Issue by swainshashwat** [sandipbhuyan/trAIn#6]
- [x] Define a structure for the Graph module
- [x] Column-wise distribution graphs for numerical columns
- [x] heat-map for missing values
- [x] Target class pie chart
